version: '3.8'
services:
  database:
    image: postgres:13
    container_name: database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: wordle
    networks:
      - APInetwork
networks:
  APInetwork: